### ISSUE TITLE
A way to allow administrator install?

### ISSUE THREAD

**Issue by MagicalDrizzle** [vegardit/scoop-portable#3]
Scoop requires you to pass `-RunAsAdmin` to the script to allow for admin install.
Would it be possible to intergrate that onto this script?

**Comment by sebthom** [comment]
I'm not sure that works well with the idea of a portable mode. Can you not use the regular scoop installer?

**Comment by MagicalDrizzle** [comment]
yeah I probably can just do that
thank you ^^
