### ISSUE TITLE
Can't install anything

### ISSUE THREAD

**Issue by YukiSuter** [vegardit/scoop-portable#7]
Attempting to install anything using the scoop environment set up by scoop-portable results in:

Can't shim 'XXXXXX.exe': File doesn't exist.

Used instructions on readme.md and simply ran "scoop install 7zip". The error occurs whether ran in command prompt, or powershell opened via cmd after running the ".cmd" file.

Install log:

```
Installing '7zip' (24.08) [64bit] from 'main' bucket
Loading 7z2408-x64.msi from cache
Checking hash of 7z2408-x64.msi ... ok.
Extracting 7z2408-x64.msi ... done.
Linking H:\Apps\Scoop\apps\7zip\current => H:\Apps\Scoop\apps\7zip\24.08
New-Item : Incorrect function
At H:\Apps\Scoop\apps\scoop\current\lib\install.ps1:1126 char:9
+         New-Item -Path $source -ItemType Junction -Value $target
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (H:\Apps\Scoop\apps\7zip\current:String) [New-Item], Win32Exception
    + FullyQualifiedErrorId : NewItemCreateIOError,Microsoft.PowerShell.Commands.NewItemCommand

Creating shim for '7z'.
Get-Command : The term '7z.exe' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At H:\Apps\Scoop\apps\scoop\current\lib\install.ps1:757 char:21
+             $bin = (Get-Command $target).Source
+                     ~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (7z.exe:String) [Get-Command], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException,Microsoft.PowerShell.Commands.GetCommandCommand

Can't shim '7z.exe': File doesn't exist.
```

**Comment by sebthom** [comment]
Scoop uses symbolic links and junctions. looks like the file system of your drive H: doesn't support this. try to install scoop in drive C: to see if it works there.

**Comment by YukiSuter** [comment]
Ok it worked on C://. The first try (H://) was a SMB share (understandable why it wouldnt work) but I've now tried it on a usb stick and the same error?

Can I ask which file systems ARE supported? I don't see the point in a portable scoop that doesnt work on portable drives?

**Comment by sebthom** [comment]
I guess you need NTFS on the USB stick and not FAT32. as I said, scoop is based around symlinks. I am using scoop portable in a [VeraCrypt](https://www.veracrypt.fr/code/VeraCrypt/) container (which is NTFS formatted) on an USB drive. Maybe you could also mount a Veracrypt container located on an SMB share and use scoop inside of that container.
